var news = [{
    titoloNews: "Accademia di Quartiere fa la sua parte per i vaccini",
    sottotitolo: "Da lunedì 21 marzo il progetto recare permetterà alle persone non autosufficienti di prenotare il trasporto verso il punto vaccinale, attivo un numero di telefono",
    testoNews: "<p style='text-align:justify'\"><b>Accademia di Quartiere vuole fare la sua parte</b> in questo momento difficile, cercando di mettere a disposizione mezzi e risorse. <b>Nell’ambito del progetto RE-CARE ha organizzato un servizio di trasporto verso le sedi vaccinali per le persone non autosufficienti. Il servizio è totalmente gratuito</b> e prevede la copertura del percorso dall’abitazione fino alla sede della vaccinazione e ovviamente anche il ritorno a casa. <b>Per potersi prenotare è necessario chiamare il numero 353-4024417 nei giorni lunedì, martedì, giovedì, venerdì e sabato dalle 11.00 alle 13.00.</b> Un’operatrice dedicata di Accademia di Quartiere si occuperà di gestire le prenotazioni e gli appuntamenti su tutto il territorio di Reggio Emilia.</p> " +
        "<p>&nbsp;</p>" +
        "<p><b>\nLe parole di Maurizio Ientile, presidente di Accademia di Quartiere\n</b></p>" +
        "<p>&nbsp;</p>" +
        "<p><b>“Accademia di Quartiere è un’associazione che opera nel quartiere stazione di Reggio Emilia e che vuole guardare con un occhio attento ai bisogni culturali indispensabili per una giusta convivenza e integrazione in una società globale e multietnica.</b> Ci occupiamo di corsi di lingua, di arti figurative, di fotografia doposcuola e laboratori ma in questo momento di sospensione abbiamo voluto <b>creare un servizio per aiutare nella campagna vaccinale. Crediamo che ognuno debba fare la sua parte con quello che può mettere a disposizione”, le parole di Maurizio Ientile, presidente di Accademia di Quartiere.</b>" +
        "<p>&nbsp;</p>" +
        "<p><b>\nCos’è RE-CARE?\n</b></p>" +
        "<p>&nbsp;</p>" +
        "<p><b>\nIl progetto RE-CARE è rivolto alla comunità di residenti ricadenti nel quartiere Stazione del Comune di Reggio Emilia e ha come obiettivo quello di offrire servizi di prossimità ai residenti in un contesto urbano composito dove frammentazione e precarietà abitativa hanno allentato vincoli di solidarietà e di vicinato un tempo presenti.</b> Oggi i bisogni di questi residenti si sostanziano nella necessità di un ausilio nella conciliazione tra tempi di vita ed esigenze di lavoro, di spostamento, di attività didattiche e ludiche per i minori, così come per anziani, cui i servizi già presenti sul territorio non sono in condizione di fornire risposte compiute. <b>I servizi ideati riguardano il recapito a domicilio della spesa alimentare, di farmaci e di libri; l’accompagnamento dei minori a scuola, alle attività extrascolastiche ludiche e di formazione; l’accompagnamento di anziani indipendenti ma non autonomi dal punto di vista della mobilità urbana verso luoghi ricreativi; l’attivazione di iniziative di bookcrossing itinerante.</b> A tutto questo ora si aggiunge anche questo nuovo servizio dedicato alla vaccinazione che si spera possa aiutare a diminuire la distanza tra le persone in questo importante appuntamento.</p>"
}];
